/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tickets: Ticket;
    features: Feature;
    'feature-categories': FeatureCategory;
    platforms: Platform;
    parcours: Parcour;
    partners: Partner;
    'partner-clients': PartnerClient;
    'client-contacts': ClientContact;
    'point-transactions': PointTransaction;
    missions: Mission;
    'mission-submissions': MissionSubmission;
    rewards: Reward;
    'reward-orders': RewardOrder;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    partners: {
      clients: 'partner-clients';
      ledger: 'point-transactions';
    };
    'partner-clients': {
      contacts: 'client-contacts';
    };
  };
  collectionsSelect: {
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'feature-categories': FeatureCategoriesSelect<false> | FeatureCategoriesSelect<true>;
    platforms: PlatformsSelect<false> | PlatformsSelect<true>;
    parcours: ParcoursSelect<false> | ParcoursSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'partner-clients': PartnerClientsSelect<false> | PartnerClientsSelect<true>;
    'client-contacts': ClientContactsSelect<false> | ClientContactsSelect<true>;
    'point-transactions': PointTransactionsSelect<false> | PointTransactionsSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    'mission-submissions': MissionSubmissionsSelect<false> | MissionSubmissionsSelect<true>;
    rewards: RewardsSelect<false> | RewardsSelect<true>;
    'reward-orders': RewardOrdersSelect<false> | RewardOrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  subject?: string | null;
  description?: string | null;
  messages?:
    | {
        author?: ('client' | 'support') | null;
        body?: string | null;
        sentAt?: string | null;
        cc?: string | null;
        attachments?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  status?: ('new' | 'acknowledged' | 'in_progress' | 'on_hold' | 'resolved') | null;
  priority?: ('urgent' | 'high' | 'normal' | 'low') | null;
  type?: ('assistance' | 'suggestion' | 'autre') | null;
  service?: ('technique' | 'facturation' | 'support' | 'commercial' | 'autre') | null;
  /**
   * Visible uniquement en interne — jamais inclus dans les e-mails.
   */
  internalNotes?: string | null;
  email: string;
  name?: string | null;
  firstName?: string | null;
  company?: string | null;
  url?: string | null;
  attachments?: (number | Media)[] | null;
  resolvedAt?: string | null;
  needsAttention?: boolean | null;
  unreadClientReply?: boolean | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Nom interne de la feature (sert de titre à la fiche).
   */
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  /**
   * Peut différer du titre interne. Laissez vide pour réutiliser le titre.
   */
  titleFeature?: string | null;
  /**
   * Résumé d'une phrase (listes, résultats de recherche).
   */
  shortDescription?: string | null;
  /**
   * Termes de recherche alternatifs (ex : masquer panneau).
   */
  keywords?: string[] | null;
  /**
   * Texte d'intro de la fiche, avant les parties détaillées ci-dessous.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  doc?:
    | {
        titleDoc?: string | null;
        descriptionDoc?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Ajoutez un GIF animé (bloc « Image / GIF »), une image, une galerie ou un fichier. Laissez vide si la partie n'a pas de visuel.
         */
        mediaDoc?:
          | (
              | {
                  /**
                   * PNG, JPG ou GIF animé (démonstration de la partie).
                   */
                  image: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'img';
                }
              | {
                  images: (number | Media)[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'galerie';
                }
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'editeur';
                }
              | {
                  file: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'fichier';
                }
            )[]
          | null;
        /**
         * Placement du média par rapport à la description (sur le front).
         */
        mediaPosition?: ('droite' | 'gauche') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visuel de couverture (listes, cartes, résultats de recherche).
   */
  thumbnail?: (number | null) | Media;
  availability?: ('disponible' | 'beta' | 'prochainement') | null;
  platforms?: (number | Platform)[] | null;
  categories?: (number | FeatureCategory)[] | null;
  /**
   * Votes « utile / pas utile » recueillis sur le front (lecture seule).
   */
  feedback?: {
    helpful?: number | null;
    notHelpful?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms".
 */
export interface Platform {
  id: number;
  name: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories".
 */
export interface FeatureCategory {
  id: number;
  name: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  description?: string | null;
  /**
   * Laisser vide pour une catégorie racine (= plateforme : Web / Mobile).
   */
  parent?: (number | null) | FeatureCategory;
  /**
   * Emplacement dans l'arborescence. Calculé automatiquement.
   */
  pathTitle?: string | null;
  sortKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcours".
 */
export interface Parcour {
  id: number;
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  /**
   * Tri croissant (équivalent menu_order WP).
   */
  order?: number | null;
  profil?: ('admin' | 'conducteur' | 'chef-chantier' | 'compagnon') | null;
  intro?: string | null;
  /**
   * L'ordre des features définit l'ordre des étapes.
   */
  steps: (number | Feature)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  displayName?: string | null;
  /**
   * Photo / logo du partenaire.
   */
  avatar?: (number | null) | Media;
  /**
   * Métier = payé en commission via un contrat. Utilisateur = personne individuelle qui gagne des points.
   */
  partnerKind?: ('metier' | 'utilisateur') | null;
  name?: string | null;
  firstName?: string | null;
  email: string;
  phone?: string | null;
  societe?: string | null;
  mobile?: string | null;
  contactName?: string | null;
  contactRole?: string | null;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  siret?: string | null;
  vatNumber?: string | null;
  legalForm?: string | null;
  headcount?: number | null;
  /**
   * Détermine automatiquement le taux et la durée de commission.
   */
  partnershipModel?: ('apporteur-affaires' | 'revendeur' | 'revendeur-sav') | null;
  commissionRate?: number | null;
  /**
   * Pré-remplie automatiquement quand tu choisis le modèle (modifiable ensuite). Videz pour re-déduire.
   */
  commissionDuration?: ('24m' | 'vie') | null;
  contractSigned?: boolean | null;
  contractSignatureDate?: string | null;
  contractStartDate?: string | null;
  /**
   * Pour un modèle 24 mois. Laisser vide si « à vie ».
   */
  contractEndDate?: string | null;
  /**
   * PDF du contrat signé.
   */
  contractDocument?: (number | null) | Media;
  /**
   * Avenants, annexes, pièces justificatives…
   */
  contractAttachments?: (number | Media)[] | null;
  contractNotes?: string | null;
  joinedAt?: string | null;
  acquisitionSource?: ('recommandation' | 'salon' | 'prospection' | 'site-web' | 'reseaux-sociaux' | 'autre') | null;
  tier?: ('bronze' | 'argent' | 'or') | null;
  /**
   * Commercial / interlocuteur TIM qui suit ce partenaire.
   */
  accountManager?: (number | null) | User;
  /**
   * Étiquettes libres (ex. prioritaire, région Sud…).
   */
  tags?: string[] | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  clients?: {
    docs?: (number | PartnerClient)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  ledger?: {
    docs?: (number | PointTransaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  code?: string | null;
  status?: ('active' | 'paused' | 'archived') | null;
  appUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Affichée comme avatar du compte.
   */
  avatar?: (number | null) | Media;
  firstName?: string | null;
  lastName?: string | null;
  name?: string | null;
  roles?: ('super-admin' | 'admin' | 'partner-metier' | 'partner-utilisateur' | 'support')[] | null;
  /**
   * Fiche partenaire rattachée à ce compte (rôles partenaire uniquement).
   */
  partner?: (number | null) | Partner;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-clients".
 */
export interface PartnerClient {
  id: number;
  companyName: string;
  partner: number | Partner;
  clientStatus?: ('prospect' | 'en-cours' | 'en-test' | 'actif' | 'resilie' | 'archive') | null;
  /**
   * Fin du contrat / de l'abonnement mensuel — la commission du partenaire s'arrête à cette date.
   */
  resiliationDate?: string | null;
  /**
   * Nom officiel de l'entreprise (pour la facture).
   */
  raisonSociale?: string | null;
  siren?: string | null;
  vatNumber?: string | null;
  /**
   * Requis — envoi des factures.
   */
  email: string;
  billingAddress?: string | null;
  billingAddressComplement?: string | null;
  phone?: string | null;
  /**
   * Nom du destinataire de la facture (optionnel).
   */
  recipient?: string | null;
  /**
   * Optionnel.
   */
  billingRemarks?: string | null;
  licences?: {
    adminQty?: number | null;
    adminPrice?: number | null;
    conducteurQty?: number | null;
    conducteurPrice?: number | null;
    chefChantierQty?: number | null;
    chefChantierPrice?: number | null;
    chefEquipeQty?: number | null;
    chefEquipePrice?: number | null;
    compagnonQty?: number | null;
    compagnonPrice?: number | null;
  };
  paymentMethod?: ('prelevement-gocardless' | 'virement') | null;
  /**
   * Délai de règlement du virement.
   */
  paymentTerms?: ('1er-du-mois' | '7j' | '15j' | '30j' | '45j' | '60j') | null;
  signatureDate?: string | null;
  /**
   * PDF du contrat signé avec le client.
   */
  contractDocument?: (number | null) | Media;
  /**
   * Enregistrez d'abord la fiche client, puis cliquez « Créer un Contact » pour ajouter les personnes à contacter chez ce client.
   */
  contacts?: {
    docs?: (number | ClientContact)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  history?:
    | {
        at?: string | null;
        totalLicences?: number | null;
        caHT?: number | null;
        commissionRate?: number | null;
        commission?: number | null;
        detail?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  totalLicences?: number | null;
  caPaye?: number | null;
  commissionMonthly?: number | null;
  caBrut?: number | null;
  discountPct?: number | null;
  statusRank?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-contacts".
 */
export interface ClientContact {
  id: number;
  client: number | PartnerClient;
  firstName?: string | null;
  lastName?: string | null;
  role?: string | null;
  email?: string | null;
  phone?: string | null;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions".
 */
export interface PointTransaction {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  partner: number | Partner;
  /**
   * > 0 crédit, < 0 débit.
   */
  delta: number;
  motif: string;
  source?: ('contrat' | 'avis' | 'ajustement' | 'echange') | null;
  /**
   * Lien technique interne (ex : order:123, submission:45). Optionnel.
   */
  ref?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: number;
  title: string;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  steps?:
    | {
        title: string;
        detail?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  proofHint?: string | null;
  logo?: (number | null) | Media;
  points?: number | null;
  type?: ('preuve' | 'manuelle') | null;
  /**
   * Optionnel (ex : page d'avis).
   */
  url?: string | null;
  order?: number | null;
  /**
   * Décoché = validable une seule fois par partenaire.
   */
  repeatable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-submissions".
 */
export interface MissionSubmission {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  mission: number | Mission;
  partner: number | Partner;
  note?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  /**
   * Optionnel (contexte avis).
   */
  reviewerEmail?: string | null;
  attachments?: (number | Media)[] | null;
  /**
   * Garde-fou anti double-crédit.
   */
  credited?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards".
 */
export interface Reward {
  id: number;
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ce que la récompense coûte à TIM. Jamais visible par un partenaire.
   */
  purchasePrice?: number | null;
  supplier?: string | null;
  image?: (number | null) | Media;
  cost: number;
  /**
   * -1 = illimité, 0 = épuisé (masqué du catalogue).
   */
  stock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-orders".
 */
export interface RewardOrder {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  partner: number | Partner;
  reward: number | Reward;
  /**
   * Défini automatiquement par la récompense choisie.
   */
  cost: number;
  status?: ('pending' | 'approved' | 'shipped' | 'delivered' | 'cancelled') | null;
  /**
   * Ligne du ledger correspondant au débit.
   */
  ledgerTransaction?: (number | null) | PointTransaction;
  /**
   * Garde-fou anti double-remboursement.
   */
  refunded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'feature-categories';
        value: number | FeatureCategory;
      } | null)
    | ({
        relationTo: 'platforms';
        value: number | Platform;
      } | null)
    | ({
        relationTo: 'parcours';
        value: number | Parcour;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'client-contacts';
        value: number | ClientContact;
      } | null)
    | ({
        relationTo: 'point-transactions';
        value: number | PointTransaction;
      } | null)
    | ({
        relationTo: 'missions';
        value: number | Mission;
      } | null)
    | ({
        relationTo: 'mission-submissions';
        value: number | MissionSubmission;
      } | null)
    | ({
        relationTo: 'rewards';
        value: number | Reward;
      } | null)
    | ({
        relationTo: 'reward-orders';
        value: number | RewardOrder;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  subject?: T;
  description?: T;
  messages?:
    | T
    | {
        author?: T;
        body?: T;
        sentAt?: T;
        cc?: T;
        attachments?: T;
        id?: T;
      };
  number?: T;
  status?: T;
  priority?: T;
  type?: T;
  service?: T;
  internalNotes?: T;
  email?: T;
  name?: T;
  firstName?: T;
  company?: T;
  url?: T;
  attachments?: T;
  resolvedAt?: T;
  needsAttention?: T;
  unreadClientReply?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  titleFeature?: T;
  shortDescription?: T;
  keywords?: T;
  content?: T;
  doc?:
    | T
    | {
        titleDoc?: T;
        descriptionDoc?: T;
        mediaDoc?:
          | T
          | {
              img?:
                | T
                | {
                    image?: T;
                    id?: T;
                    blockName?: T;
                  };
              galerie?:
                | T
                | {
                    images?: T;
                    id?: T;
                    blockName?: T;
                  };
              editeur?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              fichier?:
                | T
                | {
                    file?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        mediaPosition?: T;
        id?: T;
      };
  thumbnail?: T;
  availability?: T;
  platforms?: T;
  categories?: T;
  feedback?:
    | T
    | {
        helpful?: T;
        notHelpful?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories_select".
 */
export interface FeatureCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  pathTitle?: T;
  sortKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms_select".
 */
export interface PlatformsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcours_select".
 */
export interface ParcoursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  profil?: T;
  intro?: T;
  steps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  partnerKind?: T;
  name?: T;
  firstName?: T;
  email?: T;
  phone?: T;
  societe?: T;
  mobile?: T;
  contactName?: T;
  contactRole?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  siret?: T;
  vatNumber?: T;
  legalForm?: T;
  headcount?: T;
  partnershipModel?: T;
  commissionRate?: T;
  commissionDuration?: T;
  contractSigned?: T;
  contractSignatureDate?: T;
  contractStartDate?: T;
  contractEndDate?: T;
  contractDocument?: T;
  contractAttachments?: T;
  contractNotes?: T;
  joinedAt?: T;
  acquisitionSource?: T;
  tier?: T;
  accountManager?: T;
  tags?: T;
  notes?: T;
  clients?: T;
  ledger?: T;
  code?: T;
  status?: T;
  appUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-clients_select".
 */
export interface PartnerClientsSelect<T extends boolean = true> {
  companyName?: T;
  partner?: T;
  clientStatus?: T;
  resiliationDate?: T;
  raisonSociale?: T;
  siren?: T;
  vatNumber?: T;
  email?: T;
  billingAddress?: T;
  billingAddressComplement?: T;
  phone?: T;
  recipient?: T;
  billingRemarks?: T;
  licences?:
    | T
    | {
        adminQty?: T;
        adminPrice?: T;
        conducteurQty?: T;
        conducteurPrice?: T;
        chefChantierQty?: T;
        chefChantierPrice?: T;
        chefEquipeQty?: T;
        chefEquipePrice?: T;
        compagnonQty?: T;
        compagnonPrice?: T;
      };
  paymentMethod?: T;
  paymentTerms?: T;
  signatureDate?: T;
  contractDocument?: T;
  contacts?: T;
  history?:
    | T
    | {
        at?: T;
        totalLicences?: T;
        caHT?: T;
        commissionRate?: T;
        commission?: T;
        detail?: T;
        id?: T;
      };
  notes?: T;
  totalLicences?: T;
  caPaye?: T;
  commissionMonthly?: T;
  caBrut?: T;
  discountPct?: T;
  statusRank?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-contacts_select".
 */
export interface ClientContactsSelect<T extends boolean = true> {
  client?: T;
  firstName?: T;
  lastName?: T;
  role?: T;
  email?: T;
  phone?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions_select".
 */
export interface PointTransactionsSelect<T extends boolean = true> {
  number?: T;
  partner?: T;
  delta?: T;
  motif?: T;
  source?: T;
  ref?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  title?: T;
  instructions?: T;
  steps?:
    | T
    | {
        title?: T;
        detail?: T;
        url?: T;
        id?: T;
      };
  proofHint?: T;
  logo?: T;
  points?: T;
  type?: T;
  url?: T;
  order?: T;
  repeatable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-submissions_select".
 */
export interface MissionSubmissionsSelect<T extends boolean = true> {
  number?: T;
  mission?: T;
  partner?: T;
  note?: T;
  status?: T;
  reviewerEmail?: T;
  attachments?: T;
  credited?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards_select".
 */
export interface RewardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  purchasePrice?: T;
  supplier?: T;
  image?: T;
  cost?: T;
  stock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-orders_select".
 */
export interface RewardOrdersSelect<T extends boolean = true> {
  number?: T;
  partner?: T;
  reward?: T;
  cost?: T;
  status?: T;
  ledgerTransaction?: T;
  refunded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  firstName?: T;
  lastName?: T;
  name?: T;
  roles?: T;
  partner?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}