/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tickets: Ticket;
    features: Feature;
    'feature-categories': FeatureCategory;
    platforms: Platform;
    parcours: Parcour;
    partners: Partner;
    'partner-clients': PartnerClient;
    'client-contacts': ClientContact;
    'client-activities': ClientActivity;
    'email-templates': EmailTemplate;
    'point-transactions': PointTransaction;
    missions: Mission;
    'mission-submissions': MissionSubmission;
    rewards: Reward;
    'reward-orders': RewardOrder;
    'journey-runs': JourneyRun;
    'marketing-journeys': MarketingJourney;
    'sequence-runs': SequenceRun;
    'mailbox-connections': MailboxConnection;
    sequences: Sequence;
    forms: Form;
    'form-submissions': FormSubmission;
    'email-suppressions': EmailSuppression;
    'client-employees': ClientEmployee;
    'client-sites': ClientSite;
    'client-vehicles': ClientVehicle;
    'client-machines': ClientMachine;
    'client-portal-accounts': ClientPortalAccount;
    'calendar-connections': CalendarConnection;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    partners: {
      clients: 'partner-clients';
      ledger: 'point-transactions';
    };
    'partner-clients': {
      portalAccounts: 'client-portal-accounts';
      contacts: 'client-contacts';
    };
    'journey-runs': {
      tickets: 'tickets';
    };
  };
  collectionsSelect: {
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'feature-categories': FeatureCategoriesSelect<false> | FeatureCategoriesSelect<true>;
    platforms: PlatformsSelect<false> | PlatformsSelect<true>;
    parcours: ParcoursSelect<false> | ParcoursSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'partner-clients': PartnerClientsSelect<false> | PartnerClientsSelect<true>;
    'client-contacts': ClientContactsSelect<false> | ClientContactsSelect<true>;
    'client-activities': ClientActivitiesSelect<false> | ClientActivitiesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'point-transactions': PointTransactionsSelect<false> | PointTransactionsSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    'mission-submissions': MissionSubmissionsSelect<false> | MissionSubmissionsSelect<true>;
    rewards: RewardsSelect<false> | RewardsSelect<true>;
    'reward-orders': RewardOrdersSelect<false> | RewardOrdersSelect<true>;
    'journey-runs': JourneyRunsSelect<false> | JourneyRunsSelect<true>;
    'marketing-journeys': MarketingJourneysSelect<false> | MarketingJourneysSelect<true>;
    'sequence-runs': SequenceRunsSelect<false> | SequenceRunsSelect<true>;
    'mailbox-connections': MailboxConnectionsSelect<false> | MailboxConnectionsSelect<true>;
    sequences: SequencesSelect<false> | SequencesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'email-suppressions': EmailSuppressionsSelect<false> | EmailSuppressionsSelect<true>;
    'client-employees': ClientEmployeesSelect<false> | ClientEmployeesSelect<true>;
    'client-sites': ClientSitesSelect<false> | ClientSitesSelect<true>;
    'client-vehicles': ClientVehiclesSelect<false> | ClientVehiclesSelect<true>;
    'client-machines': ClientMachinesSelect<false> | ClientMachinesSelect<true>;
    'client-portal-accounts': ClientPortalAccountsSelect<false> | ClientPortalAccountsSelect<true>;
    'calendar-connections': CalendarConnectionsSelect<false> | CalendarConnectionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  /**
   * Pièces internes rattachées à cette demande. Le client ne les voit pas — elles ne partent dans aucun e-mail. Comme les pièces jointes du fil, elles sont supprimées 30 jours après la résolution du ticket.
   */
  documents?:
    | {
        file: number | Media;
        /**
         * Ce qu'on cherchera dans six mois. À défaut, le nom du fichier.
         */
        label?: string | null;
        /**
         * D'où vient cette pièce, ce qu'elle montre.
         */
        note?: string | null;
        addedAt?: string | null;
        addedBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  subject?: string | null;
  description?: string | null;
  messages?:
    | {
        author?: ('client' | 'support') | null;
        body?: string | null;
        sentAt?: string | null;
        cc?: string | null;
        attachments?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  status?: ('new' | 'acknowledged' | 'in_progress' | 'on_hold' | 'resolved') | null;
  priority?: ('urgent' | 'high' | 'normal' | 'low') | null;
  type?: ('assistance' | 'suggestion' | 'autre') | null;
  service?: ('technique' | 'facturation' | 'support' | 'commercial' | 'autre') | null;
  /**
   * Visible uniquement en interne — jamais inclus dans les e-mails.
   */
  internalNotes?: string | null;
  email: string;
  name?: string | null;
  firstName?: string | null;
  company?: string | null;
  url?: string | null;
  attachments?: (number | Media)[] | null;
  /**
   * Parcours dont ce ticket est issu.
   */
  journeyRun?: (number | null) | JourneyRun;
  resolvedAt?: string | null;
  needsAttention?: boolean | null;
  unreadClientReply?: boolean | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Affichée comme avatar du compte.
   */
  avatar?: (number | null) | Media;
  firstName?: string | null;
  lastName?: string | null;
  name?: string | null;
  roles?: ('super-admin' | 'admin' | 'partner-metier' | 'partner-utilisateur' | 'support')[] | null;
  /**
   * Fiche partenaire rattachée à ce compte (rôles partenaire uniquement).
   */
  partner?: (number | null) | Partner;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  displayName?: string | null;
  /**
   * Photo / logo du partenaire.
   */
  avatar?: (number | null) | Media;
  /**
   * Métier = payé en commission via un contrat. Utilisateur = personne individuelle qui gagne des points.
   */
  partnerKind?: ('metier' | 'utilisateur') | null;
  name?: string | null;
  firstName?: string | null;
  email: string;
  phone?: string | null;
  societe?: string | null;
  mobile?: string | null;
  contactName?: string | null;
  contactRole?: string | null;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  siret?: string | null;
  vatNumber?: string | null;
  legalForm?: string | null;
  headcount?: number | null;
  /**
   * Détermine automatiquement le taux et la durée de commission.
   */
  partnershipModel?: ('apporteur-affaires' | 'revendeur' | 'revendeur-sav') | null;
  commissionRate?: number | null;
  /**
   * Pré-remplie automatiquement quand tu choisis le modèle (modifiable ensuite). Videz pour re-déduire.
   */
  commissionDuration?: ('24m' | 'vie') | null;
  contractSigned?: boolean | null;
  contractSignatureDate?: string | null;
  contractStartDate?: string | null;
  /**
   * Pour un modèle 24 mois. Laisser vide si « à vie ».
   */
  contractEndDate?: string | null;
  /**
   * PDF du contrat signé.
   */
  contractDocument?: (number | null) | Media;
  /**
   * Avenants, annexes, pièces justificatives…
   */
  contractAttachments?: (number | Media)[] | null;
  contractNotes?: string | null;
  signatureJobTitle?: string | null;
  /**
   * Affichée à côté de la fonction.
   */
  signatureCompany?: string | null;
  signaturePhone?: string | null;
  signatureWebsite?: string | null;
  /**
   * Affichée en rond à gauche de la signature. À défaut, la photo de profil est utilisée.
   */
  signaturePhoto?: (number | null) | Media;
  scheduling?: {
    /**
     * Décoché, le client ne voit aucun créneau et le rendez-vous se cale hors de l'outil.
     */
    enabled?: boolean | null;
    /**
     * Soit TIM propose vos créneaux (agenda connecté), soit vous gardez votre propre outil de réservation.
     */
    mode?: ('creneaux' | 'lien') | null;
    /**
     * Le client sera renvoyé vers ce lien. La date retenue ne remonte pas automatiquement dans TIM : renseignez-la sur la phase de test si vous voulez la suivre.
     */
    bookingUrl?: string | null;
    hours?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    dateOverrides?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    durationMin?: number | null;
    /**
     * Entre deux rendez-vous.
     */
    bufferMin?: number | null;
    /**
     * Pas de réservation à la dernière minute.
     */
    minNoticeHours?: number | null;
    /**
     * Jusqu'où le client peut réserver.
     */
    horizonDays?: number | null;
  };
  joinedAt?: string | null;
  acquisitionSource?: ('recommandation' | 'salon' | 'prospection' | 'site-web' | 'reseaux-sociaux' | 'autre') | null;
  tier?: ('bronze' | 'argent' | 'or') | null;
  /**
   * Commercial / interlocuteur TIM qui suit ce partenaire.
   */
  accountManager?: (number | null) | User;
  /**
   * Étiquettes libres (ex. prioritaire, région Sud…).
   */
  tags?: string[] | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  clients?: {
    docs?: (number | PartnerClient)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  ledger?: {
    docs?: (number | PointTransaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  code?: string | null;
  status?: ('active' | 'paused' | 'archived') | null;
  appUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-clients".
 */
export interface PartnerClient {
  id: number;
  companyName: string;
  /**
   * Contact, puis envoi des factures.
   */
  email: string;
  clientStatus?:
    | (
        | 'nouvelle'
        | 'en-qualification'
        | 'demo-programmee'
        | 'attente-engagement'
        | 'attente-longue'
        | 'en-test'
        | 'actif'
        | 'perdue'
        | 'resilie'
        | 'archive'
      )
    | null;
  partner: number | Partner;
  /**
   * Pourquoi l'affaire s'est arrêtée.
   */
  lossReason?:
    | (
        | 'prix'
        | 'fonctionnalites'
        | 'concurrent'
        | 'budget'
        | 'cessation'
        | 'autre'
        | 'sans-reponse'
        | 'pas-le-moment'
        | 'besoin-different'
        | 'solution-interne'
        | 'test-non-concluant'
        | 'a-qualifier'
        | 'peu-utilise'
        | 'complexite'
        | 'support'
        | 'reorganisation'
      )
    | null;
  /**
   * Facultatif — ce que le motif ne dit pas.
   */
  lossReasonDetail?: string | null;
  /**
   * La commission du partenaire s'arrête à cette date.
   */
  resiliationDate?: string | null;
  source?: ('manuelle' | 'site-vitrine-seo' | 'google-ads-sea' | 'site-vitrine') | null;
  /**
   * Déclaré au formulaire du site vitrine.
   */
  collaborateurs?: string | null;
  formSubmission?: (number | null) | FormSubmission;
  brevoDealId?: string | null;
  /**
   * Repris du formulaire du site vitrine.
   */
  leadNotes?: string | null;
  licences?: {
    adminQty?: number | null;
    adminPrice?: number | null;
    conducteurQty?: number | null;
    conducteurPrice?: number | null;
    chefChantierQty?: number | null;
    chefChantierPrice?: number | null;
    chefEquipeQty?: number | null;
    chefEquipePrice?: number | null;
    compagnonQty?: number | null;
    compagnonPrice?: number | null;
  };
  paymentMethod?: ('prelevement-gocardless' | 'virement') | null;
  /**
   * Délai de règlement du virement.
   */
  paymentTerms?: ('1er-du-mois' | '7j' | '15j' | '30j' | '45j' | '60j') | null;
  signatureDate?: string | null;
  /**
   * Début de l'abonnement mensuel : le CA et la commission ne comptent qu'à partir de cette date.
   */
  contractStartDate?: string | null;
  /**
   * PDF du contrat signé avec le client.
   */
  contractDocument?: (number | null) | Media;
  /**
   * Déposé par le client depuis son espace. Téléchargez-le pour l'ajouter à son compte de test.
   */
  logo?: (number | null) | Media;
  /**
   * « Transmis » = le client a fini sa saisie ; « Validé » = TIM a contrôlé.
   */
  onboardingStatus?: ('en-cours' | 'transmis' | 'valide') | null;
  onboardingSubmittedAt?: string | null;
  /**
   * Un seul compte par client : l'e-mail du référent. Aucun mot de passe — un code à 6 chiffres lui est envoyé à chaque connexion.
   */
  portalAccounts?: {
    docs?: (number | ClientPortalAccount)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  contacts?: {
    docs?: (number | ClientContact)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Nom officiel de l'entreprise (pour la facture).
   */
  raisonSociale?: string | null;
  siren?: string | null;
  vatNumber?: string | null;
  billingAddress?: string | null;
  billingAddressComplement?: string | null;
  phone?: string | null;
  /**
   * Nom du destinataire de la facture (optionnel).
   */
  recipient?: string | null;
  /**
   * Optionnel.
   */
  billingRemarks?: string | null;
  history?:
    | {
        at?: string | null;
        totalLicences?: number | null;
        caHT?: number | null;
        commissionRate?: number | null;
        commission?: number | null;
        detail?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  totalLicences?: number | null;
  caPaye?: number | null;
  commissionMonthly?: number | null;
  caBrut?: number | null;
  discountPct?: number | null;
  statusRank?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ce que les visiteurs du site vitrine ont envoyé, tel qu'ils l'ont envoyé. Lecture seule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  summary?: string | null;
  form?: (number | null) | Form;
  formIdSnapshot?: string | null;
  submissionId?: string | null;
  /**
   * Valeurs postées, telles que reçues.
   */
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  channel?: ('seo' | 'sea') | null;
  placement?: ('drawer' | 'page-contact' | 'lp-hero' | 'lp-section') | null;
  /**
   * « Clic payant » est un fait ; « landing page » est une présomption. Beaucoup de présomptions = le taggage automatique de Google Ads ne remonte plus, ou le cookie d'attribution ne tient pas.
   */
  channelSource?: ('clic-payant' | 'landing-page' | 'defaut') | null;
  /**
   * Chemin de la page qui portait le formulaire.
   */
  sourcePagePath?: string | null;
  sourcePageUrl?: string | null;
  /**
   * Première page de la visite. Différente de « Page » quand la personne a navigué avant de remplir le formulaire.
   */
  landingPath?: string | null;
  lpSlug?: string | null;
  lpVariant?: string | null;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  gclid?: string | null;
  msclkid?: string | null;
  client?: (number | null) | PartnerClient;
  /**
   * « Brouillon » signale une soumission sans e-mail exploitable : la fiche existe mais n'est pas publiée.
   */
  processingStatus?: ('recue' | 'opportunite' | 'brouillon' | 'echec') | null;
  processingError?: string | null;
  ip?: string | null;
  sessionId?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les formulaires servis au site vitrine. Ce qui est saisi ici s'affiche sur le site, sans déploiement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  label: string;
  /**
   * Cité par le site vitrine et porté par chaque soumission. À ne pas modifier une fois en service.
   */
  formId: string;
  /**
   * Canal retenu quand la visite ne porte aucune trace de campagne. Un gclid ou un utm_medium=cpc réellement présent prime toujours sur cette valeur.
   */
  defaultChannel: 'seo' | 'sea';
  /**
   * L'ordre de cette liste est l'ordre d'affichage sur le site.
   */
  fields?:
    | {
        /**
         * Identifiant du champ. Il voyage dans les soumissions déjà enregistrées : le renommer rend l'historique illisible.
         */
        name: string;
        type: 'text' | 'email' | 'tel' | 'select' | 'multiselect';
        required?: boolean | null;
        label: string;
        placeholder?: string | null;
        /**
         * Affiché sous le champ. Facultatif.
         */
        helpText?: string | null;
        maxLength?: number | null;
        countryCode?: boolean | null;
        /**
         * L'ordre de cette liste est l'ordre d'affichage.
         */
        options?:
          | {
              /**
               * Stockée. À ne pas modifier.
               */
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Affiché à la place du formulaire une fois la demande envoyée.
   */
  successText: string;
  /**
   * Doit dire que l'envoi a ÉCHOUÉ. Celui de Brevo se terminait par la phrase de succès : un visiteur en échec croyait avoir réussi.
   */
  errorText: string;
  /**
   * Mention RGPD affichée près du bouton d'envoi, avec le lien vers la politique de confidentialité. Vide = rien ne s'affiche.
   */
  legalNotice?: string | null;
  /**
   * Décoché = le site vitrine ne peut plus le servir ni recevoir ses envois.
   */
  active?: boolean | null;
  seedVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-portal-accounts".
 */
export interface ClientPortalAccount {
  id: number;
  client: number | PartnerClient;
  /**
   * C'est l'identifiant : le code de connexion y est envoyé.
   */
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Décoché = le client ne peut pas demander de code. C'est la case qui OUVRE l'espace : la cocher envoie l'invitation (une seule fois) et coche l'étape du parcours. Elle se coche d'elle-même à la validation du Go/No-Go.
   */
  active?: boolean | null;
  lastLoginAt?: string | null;
  codeHash?: string | null;
  codeExpiresAt?: string | null;
  codeAttempts?: number | null;
  requestCount?: number | null;
  requestWindowStart?: string | null;
  partner?: (number | null) | Partner;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-contacts".
 */
export interface ClientContact {
  id: number;
  client: number | PartnerClient;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Décide du compte TIM créé pour cette personne.
   */
  licenceProfile?: ('admin' | 'conducteur' | 'chefChantier' | 'chefEquipe' | 'compagnon') | null;
  /**
   * Généré une fois puis FIGÉ : le client l'a distribué à ses équipes, le changer casserait des connexions.
   */
  timPassword?: string | null;
  role?: string | null;
  email?: string | null;
  phone?: string | null;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions".
 */
export interface PointTransaction {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  partner: number | Partner;
  /**
   * > 0 crédit, < 0 débit.
   */
  delta: number;
  motif: string;
  source?: ('contrat' | 'avis' | 'ajustement' | 'echange') | null;
  /**
   * Lien technique interne (ex : order:123, submission:45). Optionnel.
   */
  ref?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Une ligne par client engagé dans un parcours. La barre d'étapes se pilote depuis la fiche.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-runs".
 */
export interface JourneyRun {
  id: number;
  /**
   * Au choix du partenaire, selon son client.
   */
  sessionMode?: ('visio' | 'sur-place') | null;
  /**
   * Créé avec l'événement d'agenda, quand le client réserve son créneau. Modifiable à la main.
   */
  sessionLink?: string | null;
  /**
   * Pré-remplie avec l'adresse du client ; modifiable (autre site, agence…).
   */
  sessionLocation?: string | null;
  /**
   * Réservé par le client depuis son espace, ou saisi ici à la main. Au plus tard le lundi de démarrage. Attention : une saisie à la main ne crée PAS l'événement dans l'agenda et ne génère donc aucun lien de visio — à coller vous-même dans ce cas.
   */
  sessionAt?: string | null;
  attendeeFirstName?: string | null;
  attendeeLastName?: string | null;
  /**
   * Tel que le client l'a saisi.
   */
  attendeeRole?: string | null;
  /**
   * Pré-remplie avec celle de l'espace client, modifiable par le client si ce n'est pas lui qui suit la session.
   */
  attendeeEmail?: string | null;
  /**
   * Ajoutés par le client. Ils reçoivent l'invitation d'agenda au même titre que la personne formée.
   */
  sessionGuests?:
    | {
        email: string;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  sessionEventId?: string | null;
  extensions?:
    | {
        /**
         * 14 = 2 semaines (la fin reste un lundi).
         */
        days: number;
        at?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  decision?: ('contrat' | 'prolongation' | 'abandon') | null;
  decisionAt?: string | null;
  /**
   * Ce qui a manqué. Alimente l'analyse des tests perdus.
   */
  lostReason?: string | null;
  tickets?: {
    docs?: (number | Ticket)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  steps?:
    | {
        key: string;
        label: string;
        state?: ('a-faire' | 'auto' | 'fait' | 'bloque') | null;
        autoAt?: string | null;
        autoValidate?: boolean | null;
        actor?: ('partenaire' | 'admin' | 'client') | null;
        phase?: ('avant-test' | 'pendant-test' | 'sortie-test') | null;
        detail?: string | null;
        anchor?: ('aucun' | 'debut' | 'milieu' | 'fin' | 'session') | null;
        offsetDays?: number | null;
        doneAt?: string | null;
        doneBy?: (number | null) | User;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        key?: string | null;
        subject?: string | null;
        scheduledAt?: string | null;
        /**
         * Heure d'envoi (Paris).
         */
        sendHour?: string | null;
        /**
         * Cochée, la date ne suit plus le calendrier.
         */
        overridden?: boolean | null;
        /**
         * Renseigné à l'envoi. Un e-mail déjà parti ne repart pas.
         */
        sentAt?: string | null;
        audience?: string | null;
        anchor?: string | null;
        offsetDays?: number | null;
        stepKey?: string | null;
        trigger?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dérivé des étapes. « Perdu » et « Annulé » se posent à la main et ne sont plus recalculés.
   */
  status?: ('preparation' | 'en-cours' | 'gagne' | 'perdu' | 'annule') | null;
  notes?: string | null;
  client: number | PartnerClient;
  /**
   * Le modèle suivi. Les étapes sont copiées à la création.
   */
  journey: number | MarketingJourney;
  /**
   * Repris automatiquement du client.
   */
  partner?: (number | null) | Partner;
  /**
   * Un lundi uniquement.
   */
  startDate?: string | null;
  /**
   * 4 = lundi → lundi.
   */
  durationWeeks?: number | null;
  /**
   * Calculée.
   */
  endDate?: string | null;
  displayName?: string | null;
  autoSteps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stepsTotal?: number | null;
  stepsDone?: number | null;
  progressPct?: number | null;
  currentStepKey?: string | null;
  currentStepLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Le modèle : les étapes d'un parcours. Chaque client qui le suit obtient une phase de test dans « Phases de test ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-journeys".
 */
export interface MarketingJourney {
  id: number;
  title: string;
  /**
   * Identifiant stable référencé par le code. À ne pas modifier.
   */
  key: string;
  /**
   * À quoi sert ce parcours, en une phrase.
   */
  description?: string | null;
  /**
   * Lundi → lundi. La durée reste modifiable sur chaque phase de test.
   */
  defaultDurationWeeks?: number | null;
  /**
   * Interdit toute autre date de démarrage.
   */
  mondayOnly?: boolean | null;
  /**
   * Ordre = ordre d'exécution. Toutes les étapes sont obligatoires : le parcours avance dans cet ordre.
   */
  steps?:
    | {
        /**
         * Identifiant stable. À ne pas modifier une fois des phases lancées.
         */
        key: string;
        label: string;
        actor: 'partenaire' | 'admin' | 'client';
        phase: 'avant-test' | 'pendant-test' | 'sortie-test';
        detail?: string | null;
        /**
         * Sans effet si aucun fait observable n'est associé à cette étape. Les étapes que le logiciel sait constater (voir SYSTEM_STEPS) se valident seules de toute façon : cette règle vit dans le code, pas dans cette case.
         */
        autoValidate?: boolean | null;
        anchor?: ('aucun' | 'debut' | 'milieu' | 'fin' | 'session') | null;
        /**
         * Négatif = avant l'ancrage. Ex. -7 = une semaine avant.
         */
        offsetDays?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Objets et libellés modifiables sans déploiement. Un envoi sans échéance est déclenché par un événement (connexion, transmission du dossier…).
   */
  emails?:
    | {
        key: string;
        subject: string;
        audience?: ('client' | 'tim' | 'partenaire') | null;
        anchor?: ('aucun' | 'debut' | 'milieu' | 'fin' | 'session') | null;
        offsetDays?: number | null;
        /**
         * Heure de Paris. Une date sans heure partirait à minuit.
         */
        sendHour?: string | null;
        /**
         * Clé de l'étape sur laquelle afficher l'envoi. Obligatoire pour un envoi sans échéance ; sinon, il se rattache tout seul à l'étape correspondant à sa date.
         */
        stepKey?: string | null;
        /**
         * Le fait qui provoque l'envoi, quand il n'est pas daté.
         */
        trigger?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Décoché = ne peut plus être lancé sur de nouveaux clients.
   */
  active?: boolean | null;
  seedVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Nom interne de la feature (sert de titre à la fiche).
   */
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  /**
   * Peut différer du titre interne. Laissez vide pour réutiliser le titre.
   */
  titleFeature?: string | null;
  /**
   * Résumé d'une phrase (listes, résultats de recherche).
   */
  shortDescription?: string | null;
  /**
   * Termes de recherche alternatifs (ex : masquer panneau).
   */
  keywords?: string[] | null;
  /**
   * Texte d'intro de la fiche, avant les parties détaillées ci-dessous.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  doc?:
    | {
        titleDoc?: string | null;
        descriptionDoc?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Ajoutez un GIF animé (bloc « Image / GIF »), une image, une galerie ou un fichier. Laissez vide si la partie n'a pas de visuel.
         */
        mediaDoc?:
          | (
              | {
                  /**
                   * PNG, JPG ou GIF animé (démonstration de la partie).
                   */
                  image: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'img';
                }
              | {
                  images: (number | Media)[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'galerie';
                }
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'editeur';
                }
              | {
                  file: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'fichier';
                }
            )[]
          | null;
        /**
         * Placement du média par rapport à la description (sur le front).
         */
        mediaPosition?: ('droite' | 'gauche') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visuel de couverture (listes, cartes, résultats de recherche).
   */
  thumbnail?: (number | null) | Media;
  availability?: ('disponible' | 'beta' | 'prochainement') | null;
  platforms?: (number | Platform)[] | null;
  categories?: (number | FeatureCategory)[] | null;
  /**
   * Votes « utile / pas utile » recueillis sur le front (lecture seule).
   */
  feedback?: {
    helpful?: number | null;
    notHelpful?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms".
 */
export interface Platform {
  id: number;
  name: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories".
 */
export interface FeatureCategory {
  id: number;
  name: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  description?: string | null;
  /**
   * Laisser vide pour une catégorie racine (= plateforme : Web / Mobile).
   */
  parent?: (number | null) | FeatureCategory;
  /**
   * Emplacement dans l'arborescence. Calculé automatiquement.
   */
  pathTitle?: string | null;
  sortKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcours".
 */
export interface Parcour {
  id: number;
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  /**
   * Tri croissant (équivalent menu_order WP).
   */
  order?: number | null;
  profil?: ('admin' | 'conducteur' | 'chef-chantier' | 'compagnon') | null;
  intro?: string | null;
  /**
   * L'ordre des features définit l'ordre des étapes.
   */
  steps: (number | Feature)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Notes, e-mails, tâches et journal automatique des opportunités.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-activities".
 */
export interface ClientActivity {
  id: number;
  client: number | PartnerClient;
  type: 'note' | 'email' | 'tache' | 'systeme';
  /**
   * Quand le fait a eu lieu (pas quand il a été saisi).
   */
  occurredAt?: string | null;
  /**
   * Nom de la tâche, objet de l'e-mail, sujet de l'appel.
   */
  title?: string | null;
  content?: string | null;
  /**
   * Ce qu'il faudra faire : appeler, écrire, se voir…
   */
  taskKind?: ('appel' | 'a-faire' | 'email' | 'reunion' | 'dejeuner' | 'echeance' | 'linkedin') | null;
  dueDate?: string | null;
  /**
   * Un e-mail part à cette heure-là. Vide = pas de rappel.
   */
  reminderAt?: string | null;
  highPriority?: boolean | null;
  done?: boolean | null;
  doneAt?: string | null;
  reminderSentAt?: string | null;
  emailDirection?: ('recu' | 'envoye') | null;
  sourceMessageId?: string | null;
  capturedFrom?: string | null;
  /**
   * Noms seulement — les fichiers ne sont pas conservés.
   */
  attachmentNames?: string | null;
  recipients?: string | null;
  attachments?: (number | Media)[] | null;
  author?: (number | null) | User;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages types réutilisables lors d'un envoi depuis une opportunité. Variables disponibles : {{entreprise}}, {{contact}}, {{prenom}}, {{email}}, {{partenaire}}, {{tarifs}}, {{premier_lundi}}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * Ce qui s'affiche dans la liste de choix. Ex. « Relance sans retour ».
   */
  name: string;
  subject: string;
  /**
   * Markdown : **gras**, *italique*, # Titre, - liste. Les variables sont remplacées à l'insertion.
   */
  body: string;
  scope?: ('partenaire' | 'tim') | null;
  /**
   * Le modèle n'est proposé que sur les opportunités de ce partenaire.
   */
  partner?: (number | null) | Partner;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: number;
  title: string;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  steps?:
    | {
        title: string;
        detail?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  proofHint?: string | null;
  logo?: (number | null) | Media;
  points?: number | null;
  type?: ('preuve' | 'manuelle') | null;
  /**
   * Optionnel (ex : page d'avis).
   */
  url?: string | null;
  order?: number | null;
  /**
   * Décoché = validable une seule fois par partenaire.
   */
  repeatable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-submissions".
 */
export interface MissionSubmission {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  mission: number | Mission;
  partner: number | Partner;
  note?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  /**
   * Optionnel (contexte avis).
   */
  reviewerEmail?: string | null;
  attachments?: (number | Media)[] | null;
  /**
   * Garde-fou anti double-crédit.
   */
  credited?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards".
 */
export interface Reward {
  id: number;
  title: string;
  /**
   * Laisser vide pour générer automatiquement depuis le titre.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ce que la récompense coûte à TIM. Jamais visible par un partenaire.
   */
  purchasePrice?: number | null;
  supplier?: string | null;
  image?: (number | null) | Media;
  cost: number;
  /**
   * -1 = illimité, 0 = épuisé (masqué du catalogue).
   */
  stock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-orders".
 */
export interface RewardOrder {
  id: number;
  /**
   * Référence attribuée automatiquement ou reprise à la migration.
   */
  number?: number | null;
  partner: number | Partner;
  reward: number | Reward;
  /**
   * Défini automatiquement par la récompense choisie.
   */
  cost: number;
  status?: ('pending' | 'approved' | 'shipped' | 'delivered' | 'cancelled') | null;
  /**
   * Ligne du ledger correspondant au débit.
   */
  ledgerTransaction?: (number | null) | PointTransaction;
  /**
   * Garde-fou anti double-remboursement.
   */
  refunded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les relances après une affaire perdue. Passer le statut à « Arrêtée » interrompt les envois à venir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequence-runs".
 */
export interface SequenceRun {
  id: number;
  summary?: string | null;
  sequenceLabel?: string | null;
  client: number | PartnerClient;
  email: string;
  sequence: string;
  /**
   * « Arrêtée » interrompt tous les envois restants.
   */
  status: 'en-cours' | 'terminee' | 'arretee';
  stopReason?: ('reponse' | 'manuelle' | 'desinscription' | 'statut-change') | null;
  /**
   * Facultatif — ce que le motif ne dit pas.
   */
  stopNote?: string | null;
  startedAt?: string | null;
  /**
   * Daté à l'enrôlement. Une date modifiée décale ce message seul, pas la suite.
   */
  messages?:
    | {
        key: string;
        scheduledAt: string;
        sentAt?: string | null;
        skipped?: ('desinscrit' | 'echec') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les boîtes dont les échanges remontent dans l'historique des opportunités. Seuls les messages concernant un prospect connu sont conservés. Supprimer une ligne révoque l'accès chez Google et arrête la lecture ; les échanges déjà rattachés restent sur les fiches.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-connections".
 */
export interface MailboxConnection {
  id: number;
  accountEmail: string;
  user?: (number | null) | User;
  provider: 'google';
  /**
   * « Suspendue » arrête la lecture sans couper la connexion.
   */
  status: 'active' | 'erreur' | 'suspendue';
  lastSyncAt?: string | null;
  /**
   * Ce que Google a répondu. Une reconnexion suffit le plus souvent.
   */
  lastError?: string | null;
  /**
   * Les échanges antérieurs ne sont pas repris.
   */
  syncSince?: string | null;
  /**
   * Depuis la connexion.
   */
  capturedCount?: number | null;
  accessToken?: string | null;
  refreshToken?: string | null;
  expiresAt?: string | null;
  syncedUpTo?: string | null;
  backfillBefore?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Le modèle : quels motifs de perte ouvrent quelle séquence, et les messages qui partent ensuite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequences".
 */
export interface Sequence {
  id: number;
  label: string;
  /**
   * Citée par les séquences déjà en cours. À ne pas modifier.
   */
  key: string;
  /**
   * À quoi sert cette séquence, en une phrase.
   */
  description?: string | null;
  /**
   * Un motif ne doit apparaître que dans une seule séquence. Sans motif ici, la séquence ne s'ouvre jamais toute seule.
   */
  lossReasons?:
    | (
        | 'prix'
        | 'fonctionnalites'
        | 'concurrent'
        | 'budget'
        | 'cessation'
        | 'autre'
        | 'sans-reponse'
        | 'pas-le-moment'
        | 'besoin-different'
        | 'solution-interne'
        | 'test-non-concluant'
        | 'a-qualifier'
        | 'peu-utilise'
        | 'complexite'
        | 'support'
        | 'reorganisation'
      )[]
    | null;
  /**
   * L'ordre de cette liste est l'ordre d'envoi par défaut. Le délai de chaque message se compte depuis le précédent — et pour le premier, depuis la perte.
   */
  messages?:
    | {
        /**
         * Identifiant stable. À ne pas modifier une fois des séquences lancées.
         */
        key: string;
        /**
         * Depuis le message précédent.
         */
        delayValue: number;
        delayUnit: 'jours' | 'semaines' | 'mois';
        /**
         * « Sobre » ne garde que le texte et la signature du partenaire : ni logo, ni bandeau, ni bouton, ni pied de page. La désinscription passe par l'en-tête que la messagerie affiche elle-même, et une réponse arrête la séquence.
         */
        style: 'marketing' | 'standard';
        /**
         * Facultatif. C'est ce qui fait qu'un prospect venu pour le pointage lit d'abord le message sur le pointage.
         */
        besoin?: ('planning' | 'pointage' | 'vehicules' | 'chantiers' | 'documents-rh') | null;
        /**
         * Affiché en tête des messages marketing. Sert de repère dans la liste.
         */
        title: string;
        subject: string;
        /**
         * Affichée à droite du titre. Une capture large (environ 2 pour 1) passe mieux qu'une capture haute ; au-delà de 1,5 Mo elle mettra trop longtemps à s'afficher sur un téléphone.
         */
        image?: (number | null) | Media;
        /**
         * Trois ou quatre paragraphes courts. Pas de liste à puces : c'est ce qui fait « documentation » plutôt que message écrit par quelqu'un.
         */
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        payoff: string;
        /**
         * Un bénéfice, pas une fonctionnalité. Obligatoire pour un message marketing.
         */
        cta?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Doit être un expéditeur vérifié chez Brevo. Vide = l'adresse par défaut.
   */
  fromEmail?: string | null;
  /**
   * La ligne qui clôt le message, avant la signature. La signature elle-même vient de la fiche du partenaire de l'opportunité — elle n'est pas à saisir ici.
   */
  signature?: string | null;
  /**
   * À cocher pour une relance qui attend une réponse. À décocher pour une campagne : une réponse y est inscrite sur la fiche, mais n'interrompt pas les envois.
   */
  stopOnReply?: boolean | null;
  /**
   * Ouverte automatiquement quand tous les messages de celle-ci sont partis. Vide = la relance s'arrête là.
   */
  nextSequence?: (number | null) | Sequence;
  /**
   * Décochée = plus aucun enrôlement. Les séquences déjà en cours continuent — les interrompre se fait une par une.
   */
  active?: boolean | null;
  seedVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Adresses qui ne reçoivent plus d'envoi commercial. Les e-mails de service (tickets, accusés de réception, codes de connexion) continuent de partir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-suppressions".
 */
export interface EmailSuppression {
  id: number;
  /**
   * Enregistrée en minuscules — la casse ne doit pas créer de doublon.
   */
  email: string;
  reason: 'desinscription' | 'rejet-definitif' | 'spam' | 'manuelle';
  /**
   * Ce qui a provoqué l'inscription : lien de désinscription, événement Brevo…
   */
  source?: string | null;
  /**
   * Facultatif — le contexte, quand l'ajout est manuel.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-employees".
 */
export interface ClientEmployee {
  id: number;
  client: number | PartnerClient;
  /**
   * Généré automatiquement si laissé vide.
   */
  matricule?: string | null;
  firstName: string;
  lastName: string;
  /**
   * L'entité qui emploie ce salarié (un client peut regrouper plusieurs sociétés).
   */
  company: string;
  /**
   * Le métier réel — à ne pas confondre avec la priorité (profil de licence).
   */
  poste?: string | null;
  isUser?: boolean | null;
  /**
   * Profil de licence — détermine le prix dans le devis.
   */
  licenceProfile?: ('admin' | 'conducteur' | 'chefChantier' | 'chefEquipe' | 'compagnon') | null;
  /**
   * Requise pour les utilisateurs ; facultative pour les autres salariés.
   */
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  nationality?:
    | (
        | 'FR'
        | 'AF'
        | 'ZA'
        | 'AL'
        | 'DZ'
        | 'DE'
        | 'AD'
        | 'AO'
        | 'AG'
        | 'SA'
        | 'AR'
        | 'AM'
        | 'AU'
        | 'AT'
        | 'AZ'
        | 'BS'
        | 'BH'
        | 'BD'
        | 'BB'
        | 'BE'
        | 'BZ'
        | 'BJ'
        | 'BT'
        | 'BY'
        | 'BO'
        | 'BA'
        | 'BW'
        | 'BR'
        | 'BN'
        | 'BG'
        | 'BF'
        | 'BI'
        | 'KH'
        | 'CM'
        | 'CA'
        | 'CV'
        | 'CL'
        | 'CN'
        | 'CY'
        | 'CO'
        | 'KM'
        | 'CG'
        | 'CD'
        | 'KP'
        | 'KR'
        | 'CR'
        | 'CI'
        | 'HR'
        | 'CU'
        | 'DK'
        | 'DJ'
        | 'DM'
        | 'EG'
        | 'AE'
        | 'EC'
        | 'ER'
        | 'ES'
        | 'EE'
        | 'SZ'
        | 'VA'
        | 'US'
        | 'ET'
        | 'FJ'
        | 'FI'
        | 'GA'
        | 'GM'
        | 'GE'
        | 'GH'
        | 'GR'
        | 'GD'
        | 'GT'
        | 'GN'
        | 'GQ'
        | 'GW'
        | 'GY'
        | 'HT'
        | 'HN'
        | 'HU'
        | 'SB'
        | 'IN'
        | 'ID'
        | 'IQ'
        | 'IR'
        | 'IE'
        | 'IS'
        | 'IL'
        | 'IT'
        | 'JM'
        | 'JP'
        | 'JO'
        | 'KZ'
        | 'KE'
        | 'KG'
        | 'KI'
        | 'KW'
        | 'LA'
        | 'LS'
        | 'LV'
        | 'LB'
        | 'LR'
        | 'LY'
        | 'LI'
        | 'LT'
        | 'LU'
        | 'MK'
        | 'MG'
        | 'MY'
        | 'MW'
        | 'MV'
        | 'ML'
        | 'MT'
        | 'MA'
        | 'MU'
        | 'MR'
        | 'MX'
        | 'FM'
        | 'MD'
        | 'MC'
        | 'MN'
        | 'ME'
        | 'MZ'
        | 'MM'
        | 'NA'
        | 'NR'
        | 'NP'
        | 'NI'
        | 'NE'
        | 'NG'
        | 'NO'
        | 'NZ'
        | 'OM'
        | 'UG'
        | 'UZ'
        | 'PK'
        | 'PW'
        | 'PA'
        | 'PG'
        | 'PY'
        | 'NL'
        | 'PE'
        | 'PH'
        | 'PL'
        | 'PT'
        | 'QA'
        | 'RO'
        | 'GB'
        | 'RU'
        | 'RW'
        | 'KN'
        | 'SM'
        | 'VC'
        | 'LC'
        | 'SV'
        | 'WS'
        | 'ST'
        | 'SN'
        | 'RS'
        | 'SC'
        | 'SL'
        | 'SG'
        | 'SK'
        | 'SI'
        | 'SO'
        | 'SD'
        | 'SS'
        | 'LK'
        | 'SE'
        | 'CH'
        | 'SR'
        | 'SY'
        | 'TJ'
        | 'TZ'
        | 'TD'
        | 'CZ'
        | 'TH'
        | 'TL'
        | 'TG'
        | 'TO'
        | 'TT'
        | 'TN'
        | 'TM'
        | 'TR'
        | 'TV'
        | 'UA'
        | 'UY'
        | 'VU'
        | 'VE'
        | 'VN'
        | 'YE'
        | 'ZM'
        | 'ZW'
      )
    | null;
  birthDate?: string | null;
  contractType?: ('cdi' | 'cdd' | 'interim' | 'apprentissage' | 'stage' | 'sous-traitant') | null;
  contractEndDate?: string | null;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-sites".
 */
export interface ClientSite {
  id: number;
  client: number | PartnerClient;
  name: string;
  /**
   * La référence interne du client.
   */
  code: string;
  address: string;
  startDate: string;
  /**
   * Fin prévisionnelle si la date exacte n'est pas connue.
   */
  endDate: string;
  /**
   * Découpage interne du chantier. Facultatif.
   */
  zone?:
    | ('zone-1' | 'zone-2' | 'zone-3' | 'zone-4' | 'zone-5' | 'zone-6' | 'zone-7' | 'zone-8' | 'zone-9' | 'zone-10')
    | null;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-vehicles".
 */
export interface ClientVehicle {
  id: number;
  client: number | PartnerClient;
  brand: string;
  year: number;
  plate: string;
  /**
   * Date du certificat d'immatriculation.
   */
  registrationDate?: string | null;
  /**
   * Échéance du dernier contrôle.
   */
  inspectionDate?: string | null;
  /**
   * Échéance du contrat.
   */
  insuranceDate?: string | null;
  /**
   * Permis nécessaires pour conduire ce véhicule.
   */
  licenseTypes: string;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-machines".
 */
export interface ClientMachine {
  id: number;
  client: number | PartnerClient;
  brand: string;
  year: number;
  /**
   * Plaque si l'engin en a une, sinon n° de série.
   */
  serial: string;
  /**
   * Date du certificat d'immatriculation.
   */
  registrationDate?: string | null;
  /**
   * Échéance du dernier contrôle.
   */
  inspectionDate?: string | null;
  /**
   * Échéance du contrat.
   */
  insuranceDate?: string | null;
  /**
   * Certification nécessaire pour conduire cet engin.
   */
  cacesTypes: string;
  partner?: (number | null) | Partner;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-connections".
 */
export interface CalendarConnection {
  id: number;
  partner: number | Partner;
  provider: 'google' | 'microsoft';
  accountEmail?: string | null;
  calendars?:
    | {
        calendarId: string;
        name?: string | null;
        busy?: boolean | null;
        /**
         * Un seul agenda, celui d'où partiront les invitations : c'est son nom que le client verra comme organisateur.
         */
        target?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status?: ('ok' | 'expired') | null;
  accessToken?: string | null;
  refreshToken?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'feature-categories';
        value: number | FeatureCategory;
      } | null)
    | ({
        relationTo: 'platforms';
        value: number | Platform;
      } | null)
    | ({
        relationTo: 'parcours';
        value: number | Parcour;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'client-contacts';
        value: number | ClientContact;
      } | null)
    | ({
        relationTo: 'client-activities';
        value: number | ClientActivity;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'point-transactions';
        value: number | PointTransaction;
      } | null)
    | ({
        relationTo: 'missions';
        value: number | Mission;
      } | null)
    | ({
        relationTo: 'mission-submissions';
        value: number | MissionSubmission;
      } | null)
    | ({
        relationTo: 'rewards';
        value: number | Reward;
      } | null)
    | ({
        relationTo: 'reward-orders';
        value: number | RewardOrder;
      } | null)
    | ({
        relationTo: 'journey-runs';
        value: number | JourneyRun;
      } | null)
    | ({
        relationTo: 'marketing-journeys';
        value: number | MarketingJourney;
      } | null)
    | ({
        relationTo: 'sequence-runs';
        value: number | SequenceRun;
      } | null)
    | ({
        relationTo: 'mailbox-connections';
        value: number | MailboxConnection;
      } | null)
    | ({
        relationTo: 'sequences';
        value: number | Sequence;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'email-suppressions';
        value: number | EmailSuppression;
      } | null)
    | ({
        relationTo: 'client-employees';
        value: number | ClientEmployee;
      } | null)
    | ({
        relationTo: 'client-sites';
        value: number | ClientSite;
      } | null)
    | ({
        relationTo: 'client-vehicles';
        value: number | ClientVehicle;
      } | null)
    | ({
        relationTo: 'client-machines';
        value: number | ClientMachine;
      } | null)
    | ({
        relationTo: 'client-portal-accounts';
        value: number | ClientPortalAccount;
      } | null)
    | ({
        relationTo: 'calendar-connections';
        value: number | CalendarConnection;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  documents?:
    | T
    | {
        file?: T;
        label?: T;
        note?: T;
        addedAt?: T;
        addedBy?: T;
        id?: T;
      };
  subject?: T;
  description?: T;
  messages?:
    | T
    | {
        author?: T;
        body?: T;
        sentAt?: T;
        cc?: T;
        attachments?: T;
        id?: T;
      };
  number?: T;
  status?: T;
  priority?: T;
  type?: T;
  service?: T;
  internalNotes?: T;
  email?: T;
  name?: T;
  firstName?: T;
  company?: T;
  url?: T;
  attachments?: T;
  journeyRun?: T;
  resolvedAt?: T;
  needsAttention?: T;
  unreadClientReply?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  titleFeature?: T;
  shortDescription?: T;
  keywords?: T;
  content?: T;
  doc?:
    | T
    | {
        titleDoc?: T;
        descriptionDoc?: T;
        mediaDoc?:
          | T
          | {
              img?:
                | T
                | {
                    image?: T;
                    id?: T;
                    blockName?: T;
                  };
              galerie?:
                | T
                | {
                    images?: T;
                    id?: T;
                    blockName?: T;
                  };
              editeur?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              fichier?:
                | T
                | {
                    file?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        mediaPosition?: T;
        id?: T;
      };
  thumbnail?: T;
  availability?: T;
  platforms?: T;
  categories?: T;
  feedback?:
    | T
    | {
        helpful?: T;
        notHelpful?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories_select".
 */
export interface FeatureCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  pathTitle?: T;
  sortKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms_select".
 */
export interface PlatformsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcours_select".
 */
export interface ParcoursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  profil?: T;
  intro?: T;
  steps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  partnerKind?: T;
  name?: T;
  firstName?: T;
  email?: T;
  phone?: T;
  societe?: T;
  mobile?: T;
  contactName?: T;
  contactRole?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  siret?: T;
  vatNumber?: T;
  legalForm?: T;
  headcount?: T;
  partnershipModel?: T;
  commissionRate?: T;
  commissionDuration?: T;
  contractSigned?: T;
  contractSignatureDate?: T;
  contractStartDate?: T;
  contractEndDate?: T;
  contractDocument?: T;
  contractAttachments?: T;
  contractNotes?: T;
  signatureJobTitle?: T;
  signatureCompany?: T;
  signaturePhone?: T;
  signatureWebsite?: T;
  signaturePhoto?: T;
  scheduling?:
    | T
    | {
        enabled?: T;
        mode?: T;
        bookingUrl?: T;
        hours?: T;
        dateOverrides?: T;
        durationMin?: T;
        bufferMin?: T;
        minNoticeHours?: T;
        horizonDays?: T;
      };
  joinedAt?: T;
  acquisitionSource?: T;
  tier?: T;
  accountManager?: T;
  tags?: T;
  notes?: T;
  clients?: T;
  ledger?: T;
  code?: T;
  status?: T;
  appUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-clients_select".
 */
export interface PartnerClientsSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  clientStatus?: T;
  partner?: T;
  lossReason?: T;
  lossReasonDetail?: T;
  resiliationDate?: T;
  source?: T;
  collaborateurs?: T;
  formSubmission?: T;
  brevoDealId?: T;
  leadNotes?: T;
  licences?:
    | T
    | {
        adminQty?: T;
        adminPrice?: T;
        conducteurQty?: T;
        conducteurPrice?: T;
        chefChantierQty?: T;
        chefChantierPrice?: T;
        chefEquipeQty?: T;
        chefEquipePrice?: T;
        compagnonQty?: T;
        compagnonPrice?: T;
      };
  paymentMethod?: T;
  paymentTerms?: T;
  signatureDate?: T;
  contractStartDate?: T;
  contractDocument?: T;
  logo?: T;
  onboardingStatus?: T;
  onboardingSubmittedAt?: T;
  portalAccounts?: T;
  contacts?: T;
  raisonSociale?: T;
  siren?: T;
  vatNumber?: T;
  billingAddress?: T;
  billingAddressComplement?: T;
  phone?: T;
  recipient?: T;
  billingRemarks?: T;
  history?:
    | T
    | {
        at?: T;
        totalLicences?: T;
        caHT?: T;
        commissionRate?: T;
        commission?: T;
        detail?: T;
        id?: T;
      };
  notes?: T;
  totalLicences?: T;
  caPaye?: T;
  commissionMonthly?: T;
  caBrut?: T;
  discountPct?: T;
  statusRank?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-contacts_select".
 */
export interface ClientContactsSelect<T extends boolean = true> {
  client?: T;
  firstName?: T;
  lastName?: T;
  licenceProfile?: T;
  timPassword?: T;
  role?: T;
  email?: T;
  phone?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-activities_select".
 */
export interface ClientActivitiesSelect<T extends boolean = true> {
  client?: T;
  type?: T;
  occurredAt?: T;
  title?: T;
  content?: T;
  taskKind?: T;
  dueDate?: T;
  reminderAt?: T;
  highPriority?: T;
  done?: T;
  doneAt?: T;
  reminderSentAt?: T;
  emailDirection?: T;
  sourceMessageId?: T;
  capturedFrom?: T;
  attachmentNames?: T;
  recipients?: T;
  attachments?: T;
  author?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  body?: T;
  scope?: T;
  partner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions_select".
 */
export interface PointTransactionsSelect<T extends boolean = true> {
  number?: T;
  partner?: T;
  delta?: T;
  motif?: T;
  source?: T;
  ref?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  title?: T;
  instructions?: T;
  steps?:
    | T
    | {
        title?: T;
        detail?: T;
        url?: T;
        id?: T;
      };
  proofHint?: T;
  logo?: T;
  points?: T;
  type?: T;
  url?: T;
  order?: T;
  repeatable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-submissions_select".
 */
export interface MissionSubmissionsSelect<T extends boolean = true> {
  number?: T;
  mission?: T;
  partner?: T;
  note?: T;
  status?: T;
  reviewerEmail?: T;
  attachments?: T;
  credited?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards_select".
 */
export interface RewardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  purchasePrice?: T;
  supplier?: T;
  image?: T;
  cost?: T;
  stock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-orders_select".
 */
export interface RewardOrdersSelect<T extends boolean = true> {
  number?: T;
  partner?: T;
  reward?: T;
  cost?: T;
  status?: T;
  ledgerTransaction?: T;
  refunded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-runs_select".
 */
export interface JourneyRunsSelect<T extends boolean = true> {
  sessionMode?: T;
  sessionLink?: T;
  sessionLocation?: T;
  sessionAt?: T;
  attendeeFirstName?: T;
  attendeeLastName?: T;
  attendeeRole?: T;
  attendeeEmail?: T;
  sessionGuests?:
    | T
    | {
        email?: T;
        name?: T;
        id?: T;
      };
  sessionEventId?: T;
  extensions?:
    | T
    | {
        days?: T;
        at?: T;
        reason?: T;
        id?: T;
      };
  decision?: T;
  decisionAt?: T;
  lostReason?: T;
  tickets?: T;
  steps?:
    | T
    | {
        key?: T;
        label?: T;
        state?: T;
        autoAt?: T;
        autoValidate?: T;
        actor?: T;
        phase?: T;
        detail?: T;
        anchor?: T;
        offsetDays?: T;
        doneAt?: T;
        doneBy?: T;
        note?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        key?: T;
        subject?: T;
        scheduledAt?: T;
        sendHour?: T;
        overridden?: T;
        sentAt?: T;
        audience?: T;
        anchor?: T;
        offsetDays?: T;
        stepKey?: T;
        trigger?: T;
        detail?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  client?: T;
  journey?: T;
  partner?: T;
  startDate?: T;
  durationWeeks?: T;
  endDate?: T;
  displayName?: T;
  autoSteps?: T;
  stepsTotal?: T;
  stepsDone?: T;
  progressPct?: T;
  currentStepKey?: T;
  currentStepLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-journeys_select".
 */
export interface MarketingJourneysSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  description?: T;
  defaultDurationWeeks?: T;
  mondayOnly?: T;
  steps?:
    | T
    | {
        key?: T;
        label?: T;
        actor?: T;
        phase?: T;
        detail?: T;
        autoValidate?: T;
        anchor?: T;
        offsetDays?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        key?: T;
        subject?: T;
        audience?: T;
        anchor?: T;
        offsetDays?: T;
        sendHour?: T;
        stepKey?: T;
        trigger?: T;
        detail?: T;
        id?: T;
      };
  active?: T;
  seedVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequence-runs_select".
 */
export interface SequenceRunsSelect<T extends boolean = true> {
  summary?: T;
  sequenceLabel?: T;
  client?: T;
  email?: T;
  sequence?: T;
  status?: T;
  stopReason?: T;
  stopNote?: T;
  startedAt?: T;
  messages?:
    | T
    | {
        key?: T;
        scheduledAt?: T;
        sentAt?: T;
        skipped?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-connections_select".
 */
export interface MailboxConnectionsSelect<T extends boolean = true> {
  accountEmail?: T;
  user?: T;
  provider?: T;
  status?: T;
  lastSyncAt?: T;
  lastError?: T;
  syncSince?: T;
  capturedCount?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  syncedUpTo?: T;
  backfillBefore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequences_select".
 */
export interface SequencesSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  description?: T;
  lossReasons?: T;
  messages?:
    | T
    | {
        key?: T;
        delayValue?: T;
        delayUnit?: T;
        style?: T;
        besoin?: T;
        title?: T;
        subject?: T;
        image?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        payoff?: T;
        cta?: T;
        url?: T;
        id?: T;
      };
  fromEmail?: T;
  signature?: T;
  stopOnReply?: T;
  nextSequence?: T;
  active?: T;
  seedVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  label?: T;
  formId?: T;
  defaultChannel?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        required?: T;
        label?: T;
        placeholder?: T;
        helpText?: T;
        maxLength?: T;
        countryCode?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  successText?: T;
  errorText?: T;
  legalNotice?: T;
  active?: T;
  seedVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  summary?: T;
  form?: T;
  formIdSnapshot?: T;
  submissionId?: T;
  answers?: T;
  channel?: T;
  placement?: T;
  channelSource?: T;
  sourcePagePath?: T;
  sourcePageUrl?: T;
  landingPath?: T;
  lpSlug?: T;
  lpVariant?: T;
  referrer?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  gclid?: T;
  msclkid?: T;
  client?: T;
  processingStatus?: T;
  processingError?: T;
  ip?: T;
  sessionId?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-suppressions_select".
 */
export interface EmailSuppressionsSelect<T extends boolean = true> {
  email?: T;
  reason?: T;
  source?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-employees_select".
 */
export interface ClientEmployeesSelect<T extends boolean = true> {
  client?: T;
  matricule?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  poste?: T;
  isUser?: T;
  licenceProfile?: T;
  email?: T;
  phone?: T;
  address?: T;
  nationality?: T;
  birthDate?: T;
  contractType?: T;
  contractEndDate?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-sites_select".
 */
export interface ClientSitesSelect<T extends boolean = true> {
  client?: T;
  name?: T;
  code?: T;
  address?: T;
  startDate?: T;
  endDate?: T;
  zone?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-vehicles_select".
 */
export interface ClientVehiclesSelect<T extends boolean = true> {
  client?: T;
  brand?: T;
  year?: T;
  plate?: T;
  registrationDate?: T;
  inspectionDate?: T;
  insuranceDate?: T;
  licenseTypes?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-machines_select".
 */
export interface ClientMachinesSelect<T extends boolean = true> {
  client?: T;
  brand?: T;
  year?: T;
  serial?: T;
  registrationDate?: T;
  inspectionDate?: T;
  insuranceDate?: T;
  cacesTypes?: T;
  partner?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-portal-accounts_select".
 */
export interface ClientPortalAccountsSelect<T extends boolean = true> {
  client?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  active?: T;
  lastLoginAt?: T;
  codeHash?: T;
  codeExpiresAt?: T;
  codeAttempts?: T;
  requestCount?: T;
  requestWindowStart?: T;
  partner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-connections_select".
 */
export interface CalendarConnectionsSelect<T extends boolean = true> {
  partner?: T;
  provider?: T;
  accountEmail?: T;
  calendars?:
    | T
    | {
        calendarId?: T;
        name?: T;
        busy?: T;
        target?: T;
        id?: T;
      };
  status?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  firstName?: T;
  lastName?: T;
  name?: T;
  roles?: T;
  partner?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}