/**
 * Listes de référence du dossier de démarrage.
 *
 * Figées dans le code plutôt que calculées à l'exécution : la même liste doit
 * s'afficher dans le back-office et dans l'espace client, et une liste dérivée
 * d'`Intl` varierait avec la version de Node ou du navigateur — un salarié
 * enregistré « Türkiye » d'un côté et « Turquie » de l'autre.
 *
 * Les valeurs sont des codes ISO 3166-1 : le libellé peut être corrigé sans
 * toucher aux données déjà saisies.
 */

/** Pays de nationalité. France en tête — c'est le cas de la quasi-totalité des saisies. */
export const COUNTRIES: { label: string; value: string }[] = [
  { label: "France", value: "FR" },
  { label: "Afghanistan", value: "AF" },
  { label: "Afrique du Sud", value: "ZA" },
  { label: "Albanie", value: "AL" },
  { label: "Algérie", value: "DZ" },
  { label: "Allemagne", value: "DE" },
  { label: "Andorre", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antigua-et-Barbuda", value: "AG" },
  { label: "Arabie saoudite", value: "SA" },
  { label: "Argentine", value: "AR" },
  { label: "Arménie", value: "AM" },
  { label: "Australie", value: "AU" },
  { label: "Autriche", value: "AT" },
  { label: "Azerbaïdjan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahreïn", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbade", value: "BB" },
  { label: "Belgique", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Bénin", value: "BJ" },
  { label: "Bhoutan", value: "BT" },
  { label: "Biélorussie", value: "BY" },
  { label: "Bolivie", value: "BO" },
  { label: "Bosnie-Herzégovine", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brésil", value: "BR" },
  { label: "Brunei", value: "BN" },
  { label: "Bulgarie", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cambodge", value: "KH" },
  { label: "Cameroun", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Cap-Vert", value: "CV" },
  { label: "Chili", value: "CL" },
  { label: "Chine", value: "CN" },
  { label: "Chypre", value: "CY" },
  { label: "Colombie", value: "CO" },
  { label: "Comores", value: "KM" },
  { label: "Congo-Brazzaville", value: "CG" },
  { label: "Congo-Kinshasa", value: "CD" },
  { label: "Corée du Nord", value: "KP" },
  { label: "Corée du Sud", value: "KR" },
  { label: "Costa Rica", value: "CR" },
  { label: "Côte d’Ivoire", value: "CI" },
  { label: "Croatie", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Danemark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominique", value: "DM" },
  { label: "Égypte", value: "EG" },
  { label: "Émirats arabes unis", value: "AE" },
  { label: "Équateur", value: "EC" },
  { label: "Érythrée", value: "ER" },
  { label: "Espagne", value: "ES" },
  { label: "Estonie", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "État de la Cité du Vatican", value: "VA" },
  { label: "États-Unis", value: "US" },
  { label: "Éthiopie", value: "ET" },
  { label: "Fidji", value: "FJ" },
  { label: "Finlande", value: "FI" },
  { label: "Gabon", value: "GA" },
  { label: "Gambie", value: "GM" },
  { label: "Géorgie", value: "GE" },
  { label: "Ghana", value: "GH" },
  { label: "Grèce", value: "GR" },
  { label: "Grenade", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinée", value: "GN" },
  { label: "Guinée équatoriale", value: "GQ" },
  { label: "Guinée-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haïti", value: "HT" },
  { label: "Honduras", value: "HN" },
  { label: "Hongrie", value: "HU" },
  { label: "Îles Salomon", value: "SB" },
  { label: "Inde", value: "IN" },
  { label: "Indonésie", value: "ID" },
  { label: "Irak", value: "IQ" },
  { label: "Iran", value: "IR" },
  { label: "Irlande", value: "IE" },
  { label: "Islande", value: "IS" },
  { label: "Israël", value: "IL" },
  { label: "Italie", value: "IT" },
  { label: "Jamaïque", value: "JM" },
  { label: "Japon", value: "JP" },
  { label: "Jordanie", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kirghizstan", value: "KG" },
  { label: "Kiribati", value: "KI" },
  { label: "Koweït", value: "KW" },
  { label: "Laos", value: "LA" },
  { label: "Lesotho", value: "LS" },
  { label: "Lettonie", value: "LV" },
  { label: "Liban", value: "LB" },
  { label: "Liberia", value: "LR" },
  { label: "Libye", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lituanie", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Macédoine du Nord", value: "MK" },
  { label: "Madagascar", value: "MG" },
  { label: "Malaisie", value: "MY" },
  { label: "Malawi", value: "MW" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malte", value: "MT" },
  { label: "Maroc", value: "MA" },
  { label: "Maurice", value: "MU" },
  { label: "Mauritanie", value: "MR" },
  { label: "Mexique", value: "MX" },
  { label: "Micronésie", value: "FM" },
  { label: "Moldavie", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolie", value: "MN" },
  { label: "Monténégro", value: "ME" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar (Birmanie)", value: "MM" },
  { label: "Namibie", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Népal", value: "NP" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "Norvège", value: "NO" },
  { label: "Nouvelle-Zélande", value: "NZ" },
  { label: "Oman", value: "OM" },
  { label: "Ouganda", value: "UG" },
  { label: "Ouzbékistan", value: "UZ" },
  { label: "Pakistan", value: "PK" },
  { label: "Palaos", value: "PW" },
  { label: "Panama", value: "PA" },
  { label: "Papouasie-Nouvelle-Guinée", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Pays-Bas", value: "NL" },
  { label: "Pérou", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Pologne", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Qatar", value: "QA" },
  { label: "Roumanie", value: "RO" },
  { label: "Royaume-Uni", value: "GB" },
  { label: "Russie", value: "RU" },
  { label: "Rwanda", value: "RW" },
  { label: "Saint-Christophe-et-Niévès", value: "KN" },
  { label: "Saint-Marin", value: "SM" },
  { label: "Saint-Vincent-et-les Grenadines", value: "VC" },
  { label: "Sainte-Lucie", value: "LC" },
  { label: "Salvador", value: "SV" },
  { label: "Samoa", value: "WS" },
  { label: "Sao Tomé-et-Principe", value: "ST" },
  { label: "Sénégal", value: "SN" },
  { label: "Serbie", value: "RS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapour", value: "SG" },
  { label: "Slovaquie", value: "SK" },
  { label: "Slovénie", value: "SI" },
  { label: "Somalie", value: "SO" },
  { label: "Soudan", value: "SD" },
  { label: "Soudan du Sud", value: "SS" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Suède", value: "SE" },
  { label: "Suisse", value: "CH" },
  { label: "Suriname", value: "SR" },
  { label: "Syrie", value: "SY" },
  { label: "Tadjikistan", value: "TJ" },
  { label: "Tanzanie", value: "TZ" },
  { label: "Tchad", value: "TD" },
  { label: "Tchéquie", value: "CZ" },
  { label: "Thaïlande", value: "TH" },
  { label: "Timor oriental", value: "TL" },
  { label: "Togo", value: "TG" },
  { label: "Tonga", value: "TO" },
  { label: "Trinité-et-Tobago", value: "TT" },
  { label: "Tunisie", value: "TN" },
  { label: "Turkménistan", value: "TM" },
  { label: "Turquie", value: "TR" },
  { label: "Tuvalu", value: "TV" },
  { label: "Ukraine", value: "UA" },
  { label: "Uruguay", value: "UY" },
  { label: "Vanuatu", value: "VU" },
  { label: "Venezuela", value: "VE" },
  { label: "Viêt Nam", value: "VN" },
  { label: "Yémen", value: "YE" },
  { label: "Zambie", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
];

/**
 * Zones de chantier. Facultatif : toutes les entreprises ne découpent pas leurs
 * chantiers, et imposer une zone les obligerait à en inventer une.
 */
export const SITE_ZONES: { label: string; value: string }[] = Array.from(
  { length: 10 },
  (_, i) => ({ label: `Zone ${i + 1}`, value: `zone-${i + 1}` }),
);
